# This is a basic workflow to help you get started with Actions

name: RunParallelActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run script to get files
        run: echo "FILES=$(python .github/actions/get_files.py)" >> $GITHUB_ENV
      
      - id: set-matrix
        run: echo '::set-output name=file_matrix::${{ env.FILES }}'
      
    outputs:
      file-matrix: ${{ steps.set-matrix.outputs.file-matrix }}

  process-files:
    needs: get-files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file-name: ${{ fromJson(needs.get-files.outputs.file-matrix) }}

    steps:

      - name: Process File
        run: python .github/actions/process_file.py --file-name ${{ matrix.file }}
