name: RunParallelActions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  get-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script to get files
        id: get-files
        run: |
          FILES=$(python .github/actions/get_files.py)
          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "$FILES" > files_output.txt

      - name: Set output file matrix
        id: set-matrix
        run: |
          FILES=$(cat files_output.txt)
          echo "file-matrix=$FILES" >> $GITHUB_OUTPUT
      
    outputs:
      file-matrix: ${{ steps.set-matrix.outputs.file-matrix }}

  process-file:
    needs: get-files
    runs-on: ubuntu-latest

    strategy:
      matrix:
        file-name: ${{ fromJson(needs.get-files.outputs.file-matrix) }}

    steps:
      - uses: actions/checkout@v4

      - name: Process File
        run: python .github/actions/process_file.py --file-name ${{ matrix.file-name }}
